name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: dockerhub.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravinayag/docker-buildx:$(date +%s)
      
    - run: docker tag ravinayag/docker-buildx:$(date +%s) ravinayag/docker-buildx:latest
  
    - name: Log into registry ${{ env.REGISTRY }}
      #if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}      
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: ravinayag/docker-buildx:latest    
