name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: dockerhub.io

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravinayag/docker-buildx:$(date +%m)      
    - run: docker tag ravinayag/docker-buildx:$(date +%m) ravinayag/docker-buildx:latest
    - run: docker image ls
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: ravinayag/docker-buildx:latest    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}          
